#!/bin/bash

set ${DEBUG:+-x} -eu

SYS_PATH=/sys/class/power_supply
THRESHOLD_FILE=charge_control_end_threshold

log () {
    echo >&2 "$(date +'%Y-%m-%d %H:%M:%S') $*"
}

die () {
    log "$*"
    exit 1;
}

usage () {
    echo >&2 "
chargecfg: configure battery charging

Usage: chargecfg <COMMAND>

Known commands are:
    store   - save the relevant configuration to the persistent location
    restore - load previously saved configuration
    show    - display current configuration

Commands that take one argument:
    set_threshold <VALUE> - set charge control end threshold for
                            all supported batteries to <VALUE>
"
    exit "$1"
}

cmd_show () {
    local found='' thr_file

    cd "$SYS_PATH"
    for dirname in *; do
        thr_file="$dirname/$THRESHOLD_FILE"
        [ -f "$thr_file" ] || continue
        found=1
        echo "$thr_file: $(cat "$thr_file")"
    done

    [ -n "$found" ] || die "No supported batteries found"
    exit 0
}

cmd="${1:-}"
shift ||:

case "$cmd" in
    --help|-h|usage)
        usage 0
        ;;
    store|restore|show)
        [ "$#" == 0 ] || usage 1
        cmd_"$cmd"
        ;;
    *)
        usage 1
        ;;
esac
