#!/bin/bash

set ${DEBUG:+-x} -eu

SYS_PATH=/sys/class/power_supply
VAR_PATH=/var/lib/chargecfg
THRESHOLD_FILE=charge_control_end_threshold

log () {
    echo >&2 "chargecfg: $*"
}

die () {
    log "$*"
    exit 1;
}

usage () {
    echo >&2 "
chargecfg: configure battery charging

Usage: chargecfg <COMMAND>

Known commands are:
    store   - save the relevant configuration to the persistent location
    restore - load previously saved configuration
    show    - display current configuration

Commands that take one argument:
    set_threshold <VALUE> - set charge control end threshold for
                            all supported batteries to <VALUE>
"
    exit "$1"
}

cmd_show () {
    local found='' thr_file

    cd "$SYS_PATH"
    for dirname in *; do
        thr_file="$dirname/$THRESHOLD_FILE"
        [ -f "$thr_file" ] || continue
        found=1
        echo "$thr_file: $(cat "$thr_file")"
    done

    [ -n "$found" ] || log "No supported batteries found"
}

cmd_store () {
    local found='' thr_file

    mkdir -p "$VAR_PATH"

    cd "$SYS_PATH"
    for dirname in *; do
        thr_file="$dirname/$THRESHOLD_FILE"
        [ -f "$thr_file" ] || continue
        found=1

        mkdir -p "$VAR_PATH/$dirname"
        cat "$thr_file" > "$VAR_PATH/$thr_file"
    done

    [ -n "$found" ] || log "No supported batteries found"
    exit 0
}

cmd_restore () {
    local found='' thr_file

    cd "$SYS_PATH"
    for dirname in *; do
        thr_file="$dirname/$THRESHOLD_FILE"
        [ -f "$thr_file" ] || continue

        found=1
        if [ -r "$VAR_PATH/$thr_file" ]; then
            cat "$VAR_PATH/$thr_file" > "$thr_file"
        else
            log "Saved state for $thr_file not found, leaving the default"
        fi
    done

    [ -n "$found" ] || log "No supported batteries found"
    exit 0
}

cmd_set_threshold () {
    local value="$1" found='' thr_file

    cd "$SYS_PATH"
    for dirname in *; do
        thr_file="$dirname/$THRESHOLD_FILE"
        [ -f "$thr_file" ] || continue
        found=1
        echo "$value" > "$thr_file"
    done

    [ -n "$found" ] || log "No supported batteries found"
}


cmd="${1:-}"
shift ||:

case "$cmd" in
    --help|-h|usage)
        usage 0
        ;;
    store|restore|show)
        [ "$#" == 0 ] || usage 1
        cmd_"$cmd"
        ;;
    set_threshold)
        [ "$#" == 1 ] || usage 1
        cmd_"$cmd" "$1"
        ;;
    *)
        usage 1
        ;;
esac
